# Generated by Django 3.0.5 on 2020-04-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('manufacturing_date', models.DateField()),
                ('brand', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=50)),
            ],
        ),
    ]
